### ISSUE TITLE
Sub-Sub Commands?

### ISSUE THREAD

**Issue by DDynamic** [KennethWussmann/Levitate#21]
Hello! I came across this library and it looks really good. Could you clarify how to use subcommands and two, three, four, etc level Commands? For example Commands like:

/c money add Player Amount
/c money remove Player Amount
/c money reset Player

Also is there an easy way to have a command prefix?

Thanks and really cool librwry!

**Comment by KennethWussmann** [comment]
Hello @DDynamic,

thanks for your interest in Levitate.

You can read about the command and also sub-command registration [here](https://github.com/KennethWussmann/Levitate/wiki/2.-First-command). The more cleaner way with an annotation is explained [here](https://github.com/KennethWussmann/Levitate/wiki/4.-Complex-commands#annotation-based-registration).

You can add as many arguments to your command as you want to. (And for sure, you can add as many commands and sub-sub-sub-sub-sub commands as you want to :smile:)
```
@Command(syntax = "?c <eqi[money]> <eqi[add]> <player> <int[+]>", readable = "/c money add <Player> <Amount>", description = "Give money to a player", permission = "money.add")
public void moneyCommand(CommandSender sender, String cmd, ParameterSet args) {
  Player player = args.getPlayer(2);
  int amount = args.getInt(3);
  // Give "player" his "amount" of money.
}
```

What do you mean with command prefix? - Setting something other than `/`?
If yes, no because Levitate is only a layer between you and the Bukkit CommandHandler and Bukkit commands always start with `/`. (Except the console commands, without any `/`)
For sure, you can do something like WorldEdit:
```
@Command(syntax = "?/test <eqi[test]>", readable = "//test test")
public void testCommand(CommandSender sender, String cmd, ParameterSet args) {

}
```

Cheers,
Kenneth

**Comment by DDynamic** [comment]
Thank you!
